name: Building New Kernel

on: [push]

env:
   GIT_SECRET: ${{ secrets.GIT_SECRET }}
   GIT_USER: ${{ secrets.GIT_USER }}
   GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
   TG_TOKEN: ${{ secrets.TG_TOKEN }}
   TG_CHAT_ID: -1001711585630
   TZ: Asia/Jakarta

jobs:
  build-lancelot-r-oss-clang15:
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              KERNEL_BRANCH: -b violet-base
              DEVICE_DEFCONFIG: lancelot_defconfig
              DEVICE_CODENAME: Lancelot
              DEVICE: Redmi 9
        run: |
          git clone --depth=1 https://${GIT_USER}:${GIT_TOKEN}@github.com/rubyzee/android_kernel_xiaomi_mt6768 $KERNEL_BRANCH $DEVICE_CODENAME
          cp clang15.sh $DEVICE_CODENAME
          cd $DEVICE_CODENAME
          chmod +x clang15.sh
          bash clang15.sh
          
  build-lancelot-r-oss-proton:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              TG_TOKEN: ${{ secrets.TG_TOKEN }}
              KERNEL_BRANCH: -b violet-base
              DEVICE_DEFCONFIG: lancelot_defconfig
              DEVICE_CODENAME: Lancelot
              DEVICE: Redmi 9

        run: |
          git clone --depth=1 https://${GIT_USER}:${GIT_TOKEN}@github.com/rubyzee/android_kernel_xiaomi_mt6768 $KERNEL_BRANCH $DEVICE_CODENAME
          cp proton.sh $DEVICE_CODENAME
          cd $DEVICE_CODENAME
          chmod +x proton.sh
          bash proton.sh
          
  build-lancelot-r-oss-gcc:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              KERNEL_BRANCH: -b violet-gcc
              DEVICE_DEFCONFIG: lancelot_defconfig
              DEVICE_CODENAME: Lancelot
              DEVICE: Redmi 9
        run: |
          git clone --depth=1 https://${GIT_USER}:${GIT_TOKEN}@github.com/rubyzee/android_kernel_xiaomi_mt6768 $KERNEL_BRANCH $DEVICE_CODENAME
          cp gcc.sh $DEVICE_CODENAME
          cd $DEVICE_CODENAME
          chmod +x gcc.sh
          bash gcc.sh

  build-merlin-r-oss-clang15:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              KERNEL_BRANCH: -b violet-base
              DEVICE_DEFCONFIG: merlin_defconfig
              DEVICE_CODENAME: Merlin
              DEVICE: Redmi Note 9
        run: |
          git clone --depth=1 https://${GIT_USER}:${GIT_TOKEN}@github.com/rubyzee/android_kernel_xiaomi_mt6768 $KERNEL_BRANCH $DEVICE_CODENAME
          cp clang15.sh $DEVICE_CODENAME
          cd $DEVICE_CODENAME
          chmod +x clang15.sh
          bash clang15.sh
          
  build-merlin-r-oss-proton:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
                KERNEL_BRANCH: -b violet-base
                DEVICE_DEFCONFIG: merlin_defconfig
                DEVICE_CODENAME: Merlin
                DEVICE: Redmi Note 9
        run: |
          git clone --depth=1 https://${GIT_USER}:${GIT_TOKEN}@github.com/rubyzee/android_kernel_xiaomi_mt6768 $KERNEL_BRANCH $DEVICE_CODENAME
          cp proton.sh $DEVICE_CODENAME
          cd $DEVICE_CODENAME
          chmod +x proton.sh
          bash proton.sh
          
  build-merlin-r-oss-gcc:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              KERNEL_BRANCH: -b violet-gcc
              DEVICE_DEFCONFIG: merlin_defconfig
              DEVICE_CODENAME: Merlin
              DEVICE: Redmi Note 9
        run: |
          git clone --depth=1 https://${GIT_USER}:${GIT_TOKEN}@github.com/rubyzee/android_kernel_xiaomi_mt6768 $KERNEL_BRANCH $DEVICE_CODENAME
          cp gcc.sh $DEVICE_CODENAME
          cd $DEVICE_CODENAME
          chmod +x gcc.sh
          bash gcc.sh
