name: Building New Kernel

on: [push]

env:
   GIT_SECRET: ${{ secrets.GIT_SECRET }}
   GIT_USER: ${{ secrets.GIT_USER }}
   GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
   TG_TOKEN: ${{ secrets.TG_TOKEN }}

jobs:
  build-lancelot-r-oss-clang15:
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              GIT_USER: ${{ secrets.GIT_USER }}
              GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
              TG_TOKEN: ${{ secrets.TG_TOKEN }}
              KERNEL_BRANCH: -b violet-base
              TG_CHAT_ID: -1001711585630
              TZ: Asia/Jakarta
              DEVICE_DEFCONFIG: lancelot_defconfig
              DEVICE_CODENAME: Lancelot
              DEVICE: Redmi 9
        run: |
          chmod +x clang15.sh
          bash clang15.sh
          
  build-lancelot-r-oss-proton:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              GIT_USER: ${{ secrets.GIT_USER }}
              GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
              TG_TOKEN: ${{ secrets.TG_TOKEN }}
              KERNEL_BRANCH: -b violet-base
              TG_CHAT_ID: -1001711585630
              TZ: Asia/Jakarta
              DEVICE_DEFCONFIG: lancelot_defconfig
              DEVICE_CODENAME: Lancelot
              DEVICE: Redmi 9

        run: |
          chmod +x proton.sh
          bash proton.sh
          
  build-lancelot-r-oss-gcc:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              GIT_USER: ${{ secrets.GIT_USER }}
              GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
              TG_TOKEN: ${{ secrets.TG_TOKEN }}
              KERNEL_BRANCH: -b violet-gcc
              TG_CHAT_ID: -1001711585630
              TZ: Asia/Jakarta
              DEVICE_DEFCONFIG: lancelot_defconfig
              DEVICE_CODENAME: Lancelot
              DEVICE: Redmi 9
        run: |
          chmod +x gcc.sh
          bash gcc.sh

  build-merlin-r-oss-clang15:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              GIT_USER: ${{ secrets.GIT_USER }}
              GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
              TG_TOKEN: ${{ secrets.TG_TOKEN }}
              KERNEL_BRANCH: -b violet-base
              TG_CHAT_ID: -1001711585630
              TZ: Asia/Jakarta
              DEVICE_DEFCONFIG: merlin_defconfig
              DEVICE_CODENAME: Merlin
              DEVICE: Redmi Note 9
        run: |
          chmod +x clang15.sh
          bash clang15.sh
          
  build-merlin-r-oss-proton:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
                GIT_USER: ${{ secrets.GIT_USER }}
                GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
                TG_TOKEN: ${{ secrets.TG_TOKEN }}
                KERNEL_BRANCH: -b violet-base
                TG_CHAT_ID: -1001711585630
                TZ: Asia/Jakarta
                DEVICE_DEFCONFIG: merlin_defconfig
                DEVICE_CODENAME: Merlin
                DEVICE: Redmi Note 9
        run: |
          chmod +x proton.sh
          bash proton.sh
          
  build-merlin-r-oss-gcc:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        env:
              GIT_USER: ${{ secrets.GIT_USER }}
              GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
              TG_TOKEN: ${{ secrets.TG_TOKEN }}
              KERNEL_BRANCH: -b violet-gcc
              TG_CHAT_ID: -1001711585630
              TZ: Asia/Jakarta
              DEVICE_DEFCONFIG: merlin_defconfig
              DEVICE_CODENAME: Merlin
              DEVICE: Redmi Note 9
        run: |
          chmod +x gcc.sh
          bash gcc.sh

