name: Building New Kernel

on: [push]

jobs:
  build-lancelot-r-oss-clang15:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  KERNEL_BRANCH:violet-base
  TG_CHAT_ID:-1001711585630
  TZ: Asia/Jakarta
  DEVICE_DEFCONFIG:lancelot_defconfig
  DEVICE_CODENAME:Lancelot
  DEVICE:Redmi 9
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        run: |
          chmod +x clang15.sh
          bash clang15.sh
          
  build-lancelot-r-oss-proton:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  KERNEL_BRANCH:violet-base
  TG_CHAT_ID:-1001711585630
  TZ: Asia/Jakarta
  DEVICE_DEFCONFIG:lancelot_defconfig
  DEVICE_CODENAME:Lancelot
  DEVICE:Redmi 9

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        run: |
          chmod +x proton.sh
          bash proton.sh
          
  build-lancelot-r-oss-gcc:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  KERNEL_BRANCH:violet-gcc
  TG_CHAT_ID:-1001711585630
  TZ: Asia/Jakarta
  DEVICE_DEFCONFIG:lancelot_defconfig
  DEVICE_CODENAME:Lancelot
  DEVICE:Redmi 9

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        run: |
          chmod +x gcc.sh
          bash gcc.sh

  build-merlin-r-oss-clang15:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  KERNEL_BRANCH:violet-base
  TG_CHAT_ID:-1001711585630
  TZ: Asia/Jakarta
  DEVICE_DEFCONFIG:merlin_defconfig
  DEVICE_CODENAME:Merlin
  DEVICE:Redmi Note 9

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        run: |
          chmod +x clang15.sh
          bash clang15.sh
          
  build-merlin-r-oss-proton:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  KERNEL_BRANCH:violet-base
  TG_CHAT_ID:-1001711585630
  TZ: Asia/Jakarta
  DEVICE_DEFCONFIG:merlin_defconfig
  DEVICE_CODENAME:Merlin
  DEVICE:Redmi Note 9

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        run: |
          chmod +x proton.sh
          bash proton.sh
          
  build-lancelot-r-oss-gcc:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  KERNEL_BRANCH:violet-gcc
  TG_CHAT_ID:-1001711585630
  TZ: Asia/Jakarta
  DEVICE_DEFCONFIG:merlin_defconfig
  DEVICE_CODENAME:Lancelot
  DEVICE:Redmi Note 9

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          chmod +x setup.sh
          sudo bash setup.sh

      - name: Compile Kernel
        run: |
          chmod +x gcc.sh
          bash gcc.sh
          
